server:
  port: 8081

spring:
  application:
    name: flash-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
