global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flash-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8081']
        labels:
          service: 'flash-api'

  - job_name: 'flash-admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin:8082']
        labels:
          service: 'flash-admin'

  - job_name: 'flash-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          service: 'flash-gateway'

  - job_name: 'rocketmq-broker'
    static_configs:
      - targets: ['flash-rocketmq-broker:5557']
        labels:
          service: 'rocketmq-broker'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['flash-node-exporter:9100']
