apiVersion: 1

# Prometheus 数据源自动配置
# Grafana 启动时会自动加载此文件，无需手动添加数据源。
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://flash-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
